name: jaguar_orm_gen
description: Generator for jaguar_orm
version: 2.2.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query: ^2.2.2
  jaguar_orm: ^2.2.1
  analyzer: ^0.32.0
  build: ^0.12.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.0
  build_test: ^0.10.3
  collection: ^1.14.10
  path: ^1.6.2

#dependency_overrides:
#  jaguar_query:
#    path: ../query
#  jaguar_orm:
#    path: ../orm