name: jaguar_orm
description: Source generated ORM for SQL/NoSQL
version: 0.1.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar_query: # '>=0.0.10 <0.1.0'
    path: ../jaguar_query
  source_gen: "^0.5.1"
  build: ">=0.7.0 <0.8.0"
  yaml: ">=2.1.10 <3.0.0"
  intl: ">=0.14.0 <0.15.0"
  source_gen_help: '>=0.0.4 <0.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
