name: jaguar_orm
description: Source-generated ORM with relations (one-to-one, one-to-many, many-to-many), preloading, cascading, polymorphic relations, etc
version: 2.2.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_query: ^2.2.2
  quiver: ^2.0.0
  path: ^1.6.0

dev_dependencies:
  test: ^1.2.0
  jaguar_query_postgres: # ^0.2.5
    path: ../postgres
  build_runner: ^0.10.0
  jaguar_orm_gen:
    path: ../generator

#dependency_overrides:
#  jaguar_query:
#    path: ../query