name: jaguar_query_sqflite
description: SQFLite adapter for jaguar_query
version: 2.1.5
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

flutter:

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^0.11.0
  jaguar_query: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
