name: jaguar_query_sqljocky
description: MySQL (sqljocky) adapter for jaguar_query and jaguar_orm
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar_query: ^2.1.2
  logging:
  sqljocky5: ^1.0.0
