name: jaguar_query_sqljocky
description: MySQL (sqljocky) adapter for jaguar_query and jaguar_orm
version: 0.2.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar_query: ^0.2.1
  logging: ">=0.9.2 <0.12.0"
  sqljocky5: ^1.0.0

dev_dependencies:
  # test: '>=0.12.0 <0.13.0'
