name: jaguar_query_postgres
description: postgresql adapter for jaguar_query
version: 2.1.5
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  jaguar_query: ^2.1.9
  postgres: ^1.0.0-beta.1

dev_dependencies:
  test: ^1.2.0

dependency_overrides:
  jaguar_query:
    path: ../query
